---
title: "Trabajo Final"
output: pdf_document
date: "2024-05-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install.packages("codpostal")
library(here)
library(readxl)
library(tidyverse)
library(ggplot2)
library(visdat)
library(patchwork)
library(car)
```

```{r}
df = read_excel(here("airbnb_barcelona_v2.xlsx"))

head(df)
summary(df)
```



```{r}


df%>%vis_miss()

df= df %>% select(barrio,
                  tipo_habitacion,
                  personas,
                  banios,
                  habitaciones,
                  camas,
                  precio_euros,	
                  estancia_min,	
                  puntuacion,	 
                  TV,	 
                  Wifi,	
                  Air_conditioning,	
                  Elevator,	
                  Breakfast,	
                  Pets_allowed,	
                  Cable_TV,	
                  Pool,	
                  Patio_or_balcony,	
                  check_in_24_hs,	
                  Smart_lock)%>% filter(is.na(puntuacion)==FALSE,
                                        is.na(barrio)==FALSE)

df%>%vis_miss()
#df%>% summarise(sum_wifi=sum(Wifi),sum_int=sum(Internet))

```



```{r}

distritos<-character(length(nrow(df)))


#CON AYUDA, primero hay que sacar las observaciones que no tienen el dato del barrio para que funcione el codigo
  
for (i in seq_along(df$barrio)) {
    if (df$barrio[i] == "Sant Marta"|| 
               df$barrio[i] == "La Guineueta - Canyelles"|| 
               df$barrio[i] == "La Prosperitat"|| 
               df$barrio[i] == "Nou Barris"|| 
               df$barrio[i] == "Porta"|| 
               df$barrio[i] == "Trinitat Nova"|| 
               df$barrio[i] == "Turo de la Peira - Can Peguera"|| 
               df$barrio[i] == "Verdum - Los Roquetes"|| 
               df$barrio[i] == "Vilapicina i la Torre Llobeta") {
      distritos[i] <- "Nou Barris"
    } else if (df$barrio[i]=='La Sagrada Familia' || 
               df$barrio[i] == "Eixample" || 
               df$barrio[i] == "L'Antiga Esquerra de l'Eixample" || 
               df$barrio[i] == "Sant Antoni" || 
               df$barrio[i] == "Dreta de l'Eixample" || 
               df$barrio[i] == "La Nova Esquerra de l'Eixample" || 
               df$barrio[i] == "el Fort Pienc") {
      distritos[i] <- "L'Eixample"
    } else if (df$barrio[i] == "Vila de Gracia" || 
               df$barrio[i] == "Camp d'en Grassot i Gracia Nova" || 
               df$barrio[i] == "Gracia" || 
               df$barrio[i] == "El Coll" || 
               df$barrio[i] == "La Salut" || 
               df$barrio[i] == "Vallcarca i els Penitents") {
      distritos[i] <- "Gracia"
    } else if (df$barrio[i] == "Horta-Guinarda" ||
               df$barrio[i] == "Can Baro" ||
               df$barrio[i] == "Carmel" ||
               df$barrio[i] == "El Baix Guinardo"||
               df$barrio[i] == "Guinarda" ||
               df$barrio[i] == "Horta"||
               df$barrio[i] == "La Font d'en Fargues"||
               df$barrio[i] == "La Teixonera"||
               df$barrio[i] == "La Vall d'Hebron"||
               df$barrio[i] == "Montbau"||
               df$barrio[i] == "Sant Geni­s dels Agudells") {
      distritos[i] <- "Horta"
    } else if (df$barrio[i] == "Les Corts"|| 
               df$barrio[i] == "La Maternitat i Sant Ramon"|| 
               df$barrio[i] == "Pedralbes") {
      distritos[i] <- "Les Corts"
    } else if (df$barrio[i] == "El Gotic" || 
               df$barrio[i] == "La Barceloneta" || 
               df$barrio[i] == "Ciutat Vella" || 
               df$barrio[i] == "El Raval" || 
               df$barrio[i] == "Sant Pere/Santa Caterina" || 
               df$barrio[i] == "El Born") {
      distritos[i] <- "Ciutat Vella"
    } else if (df$barrio[i] == "El Poble-sec" || 
               df$barrio[i] == "Sants-Montjuic") {
      distritos[i] <- "Sants-Montjuic"
    } else if (df$barrio[i] == "El Clot" || 
               df$barrio[i] == "El Besos i el Maresme" || 
               df$barrio[i] == "El Camp de l'Arpa del Clot"||
               df$barrio[i] == "El Poblenou"||
               df$barrio[i] == "La Vila Olimpica"||
               df$barrio[i] == "Diagonal Mar - La Mar Bella"||
               df$barrio[i] == "Glaries - El Parc"||
               df$barrio[i] == "La Verneda i La Pau"||
               df$barrio[i] == "Provencals del Poblenou"||
               df$barrio[i] == "Sant Marta­ de Provencals"
               ) {
      distritos[i] <- "Sant Martí"
    } else if (df$barrio[i] == "Sant Gervasi - Galvany"||
               df$barrio[i] == "El Putget i Farro"||
               df$barrio[i] == "Les Tres Torres"||
               df$barrio[i] == "Sant Gervasi - la Bonanova"||
               df$barrio[i] == "Sarria"||
               df$barrio[i] == "Sarria-Sant Gervasi") {
      distritos[i] <- "Sarriá"
    } else if (df$barrio[i] == "El Bon Pastor" ||
               df$barrio[i] == "El Congres i els Indians"||
               df$barrio[i] == "La Sagrera"||
               df$barrio[i] == "La Trinitat Vella"||
               df$barrio[i] == "Navas"||
               df$barrio[i] == "Sant Andreu"||
               df$barrio[i] == "Sant Andreu de Palomar") {
      distritos[i] <- "Sant Andreau"
  }
}
df$distritos <- distritos

```



```{r}

summary(df)

df_final= df%>% mutate(tipo_habitacion=as.factor(tipo_habitacion),
                       banios=as.factor(banios),
                       camas=as.factor(camas),
                       habitaciones=as.factor(habitaciones),
                       distritos=as.factor(distritos),
                       wifi=as.factor(Wifi),
                      TV=as.factor(TV),	 
                  Wifi=as.factor(wifi),	
                  Air_conditioning=as.factor(Air_conditioning),	
                  Elevator=as.factor(Elevator),	
                  Breakfast=as.factor(Breakfast),	
                  Pets_allowed=as.factor(Pets_allowed),	
                  Cable_TV=as.factor(Cable_TV),	
                  Pool=as.factor(Pool),	
                  Patio_or_balcony=as.factor(Patio_or_balcony),	
                  check_in_24_hs=as.factor(check_in_24_hs),	
                  Smart_lock=as.factor(Smart_lock)
             )

```


```{r, echo=FALSE,warning=FALSE}
#ggplot(data=df_final) + geom_boxplot(aes(x=tipo_habitacion,y=precio_euros,fill=tipo_habitacion)) + ylab('Precio (en Euros)')+ xlab("Tipo de Habitación")

#p2=ggplot(data=df_final) + geom_point(aes(x=personas,y=precio_euros),size=0.25) + theme (axis.title.y = element_blank())

#p3=ggplot(data=df_final) + geom_point(aes(x=estancia_min,y=precio_euros),size=0.25) + theme (axis.title.y = element_blank())

#ggplot(data=df_final) + geom_point(aes(x=puntuacion,y=precio_euros)) + xlab("Puntuación")+ ylab('Precio (en Euros)')



p1=ggplot(data=df_final) + geom_boxplot(aes(x=Air_conditioning,y=precio_euros,fill=Air_conditioning)) + theme (axis.title.y = element_blank()) + xlab("Aire Acondicionado")

p3=ggplot(data=df_final) + geom_boxplot(aes(x=Wifi,y=precio_euros,fill=Wifi)) + theme (axis.title.y = element_blank()) + xlab("WiFi")
p4=ggplot(data=df_final) + geom_boxplot(aes(x=Breakfast,y=precio_euros,fill=Breakfast)) + theme (axis.title.y = element_blank()) + xlab("Desayuno")
p5=ggplot(data=df_final) + geom_boxplot(aes(x=TV,y=precio_euros,fill=TV)) + theme (axis.title.y = element_blank()) + xlab("Televisión")

p7=ggplot(data=df_final) + geom_boxplot(aes(x=Pets_allowed,y=precio_euros,fill=Pets_allowed)) + theme (axis.title.y = element_blank()) + xlab("Admite Mascotas")
p8=ggplot(data=df_final) + geom_boxplot(aes(x=check_in_24_hs,y=precio_euros,fill=check_in_24_hs)) + theme (axis.title.y = element_blank()) + xlab("Check-In 24hs")


#p3=ggplot(data=df_final) + geom_point(aes(x=cuello,y=precio_euros),size=0.25) + theme (axis.title.y = element_blank())
#p4=ggplot(data=df_final) + geom_point(aes(x=pecho,y=precio_euros),size=0.25) + theme (axis.title.y = element_blank())
#p5=ggplot(data=df_final) + geom_point(aes(x=abdomen,y=precio_euros),size=0.25) + theme (axis.title.y = element_blank())

p6=ggplot(data=df_final) + geom_boxplot(aes(x=distritos,y=precio_euros,fill=distritos)) + theme (axis.title.y = element_blank()) + xlab("Distritos")

(p1+p3+p4+p5+p7+p8)/p6

p5
```










```{r, eval=FALSE}
  

#SELECCIÓN DE VARIABLES

k=ncol(airbnb_barcelona)-1
modelos_posibles=2**k-1

#hay 16383 modelos posibles, vamos a aplicar los procedimientos de hipotesis para
#llegar al mejor modelo

# Definimos la primer versión del modelo

mod0 <- lm(precio_euros ~  distritos + tipo_habitacion+personas+ banios+ habitaciones+camas+estancia_min+puntuacion+TV+Wifi+Air_conditioning+Elevator+Breakfast+Pets_allowed+Cable_TV+Pool+Patio_or_balcony+check_in_24_hs+Smart_lock, data=df_final)

#para "vichar"
anova(mod0)
summary(mod0)

```


## Diagnóstico


```{r, echo=FALSE}
#hacer todo de diapo 4 del tercer antes de empezar a corregir
#1

## PREGUNTARRR

 df_final %>% select(Air_conditioning,Pool)


vif(mod0)
#si el VIF es alto la variable es comb lineal de las demás, gatos2, ratones tienen VIF altos (>5)

# No olvidemos ralizar la etapa de diagnostico
datos$s_i <- rstudent(mod0)
ggplot(datos, aes(x = marca, y = s_i, fill= marca)) +
  geom_boxplot() +
  xlab('Marca') + 
  ylab('residuos studentizados') +
  theme_bw()

# homoscedasticidad
library(skedastic)
breusch_pagan(mod0)
```


## ATIPICOS

```{r, echo=FALSE}

#7
# medidas de influencia
h_i <- influence(mod0)$hat
D_i <- cooks.distance(mod0)
df <- data.frame(i = 1:12848,
                 h_i = h_i,
                 D_i = D_i)

a = df %>% filter(D_i>4/12848)%>% arrange(desc(D_i)) %>% head(50) %>% pull(i)

## SACAR LOS ATIPICOS CON ESTE "-"
## FILTRAR PRIMERO TODOS LOS N/A EN LA ETAPA INICIAL
# IR SACANDO DE A POCOS POR SI APARECEN NUEVOS ATIPICOS Y VOLVER A CALCULAR

df_final[-a,]





# leverage
ggplot(df, aes(x = i, y = h_i)) +
  geom_point() +
  geom_segment(aes(x = i, xend = i, y = 0, yend = h_i)) +
  xlab('') +
  ylab(expression(h[i])) +
  geom_abline(slope = 0, intercept = 2*5/50, col = 2, linetype = 'dashed')

# Distancia de Cook
ggplot(df, aes(x = i, y = D_i)) +
  geom_point() +
  geom_segment(aes(x = i, xend = i, y = 0, yend = D_i)) +
  xlab('') +
  ylab(expression(D[i])) +
  geom_abline(slope = 0, intercept = 4/50, col = 2, linetype = 'dashed')
#si hay observaciones influyentes, en el grafico de leverage no se ve, solo se ve ruido, pero en el grafico de cook los que están por arriba de la linea roja son influyentes.


# normalidad
library(qqplotr)
ggplot(data = df_final, aes(sample = s_i)) +
  stat_qq_band(fill = 2) +
  stat_qq_line(col = 2) +
  stat_qq_point() +
  xlab("Cuantiles teoricos")+
  ylab("Cuantiles empiricos")

shapiro.test(datos$s_i)


coef(mod0)
summary(mod0)

#CUAL ES LA LIBRERIA??
#forward
modF <- forward(mod0, alpha = 0.05)
length(coef(modF))  # parametros
summary(modF)

# backward
modB <- backward(mod0, alpha = 0.01)
length(coef(modB))  # parametros
summary(modB)

# stepwise
modS <- stepWise(mod0, alpha.enter = 0.04, alpha.remove=0.05)
length(coef(modS))  # parametros
summary(modS)

#COMPARAMOS POR AIC, BIC O R2 AJUSTADO PARA VER CUAL ES EL MEJOR

#que paquete se usaba para ver la tabla con AIC BIC
install.packages("HH")
library(HH)
summaryHH(modF)
summaryHH(modB)

help(anova)
summaryHH(modS)

```


